name: ci

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  verilate:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install verilator
      run: sudo apt-get install -y verilator
    - name: verilate
      # TODO(hasheddan): replace these with Makefile targets
      run: |
        verilator -Wall -cc -Irtl top.v --exe sim/top.cpp
        make -C obj_dir -f Vtop.mk
        ./obj_dir/Vtop
        verilator -Wall -cc -Irtl alu.v --exe sim/alu.cpp
        make -C obj_dir -f Valu.mk
        ./obj_dir/Valu
