name: ci

on:
  push:
    branches:
      - main
    paths:
     - 'rtl/**'
     - 'sim/**'
  pull_request:
    paths:
     - 'rtl/**'
     - 'sim/**'
  workflow_dispatch: {}

jobs:
  verilate:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install verilator
      run: sudo apt-get install -y verilator
    - name: verilate
      run: |
        verilator -Wall -cc -Irtl top.v --exe sim/top.cpp
        make -C obj_dir -f Vtop.mk
        ./obj_dir/Vtop
